# Generated by Django 5.0.6 on 2026-04-22 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='unread', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
