# Generated by Django 5.0.6 on 2026-05-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alerts_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='user_id',
            new_name='user',
        ),
    ]
