# Generated by Django 5.0.6 on 2026-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
