# Generated by Django 5.0.6 on 2026-05-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=50),
        ),
    ]
