# Generated by Django 5.0.6 on 2026-04-22 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress_score', models.IntegerField()),
                ('anxiety_score', models.IntegerField()),
                ('burnout_score', models.IntegerField()),
                ('depression_score', models.IntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
