# Generated by Django 5.0.6 on 2026-05-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaires',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
    ]
