# Generated by Django 5.0.6 on 2026-05-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_alter_questionnaires_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaires',
            old_name='user_id',
            new_name='user',
        ),
    ]
