# Generated by Django 5.0.6 on 2026-04-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insights',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insights',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaires'),
        ),
    ]
