# Generated by Django 5.0.6 on 2026-05-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insights',
            options={'verbose_name': 'Insight', 'verbose_name_plural': 'Insights'},
        ),
    ]
