# Generated by Django 5.0.6 on 2026-05-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_alter_insights_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insights',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
    ]
